--liquibase formatted sql

--changeset elie:0001-teams
CREATE TABLE teams (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

--changeset elie:0002-users
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    team_id       BIGINT REFERENCES teams(id),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_role CHECK (role IN ('EMPLOYEE','MANAGER','ADMIN'))
);
CREATE INDEX idx_users_team ON users(team_id);

--changeset elie:0003-accounts
CREATE TABLE accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    name        VARCHAR(120) NOT NULL,
    type        VARCHAR(20)  NOT NULL,
    normal_side VARCHAR(6)   NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_accounts_type CHECK (type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
    CONSTRAINT chk_accounts_side CHECK (normal_side IN ('DEBIT','CREDIT'))
);

--changeset elie:0004-expenses
CREATE TABLE expenses (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_id     BIGINT NOT NULL REFERENCES users(id),
    team_id          BIGINT REFERENCES teams(id),
    amount           NUMERIC(14,2) NOT NULL,
    currency         CHAR(3)       NOT NULL DEFAULT 'USD',
    category         VARCHAR(20)   NOT NULL,
    description      VARCHAR(500),
    merchant         VARCHAR(150),
    status           VARCHAR(20)   NOT NULL DEFAULT 'SUBMITTED',
    spent_on         DATE          NOT NULL,
    submitted_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    decided_at       TIMESTAMPTZ,
    decided_by       BIGINT REFERENCES users(id),
    decision_comment VARCHAR(500),
    journal_entry_id BIGINT,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_expenses_amount   CHECK (amount > 0),
    CONSTRAINT chk_expenses_status   CHECK (status IN ('SUBMITTED','APPROVED','REJECTED')),
    CONSTRAINT chk_expenses_category CHECK (category IN ('TRAVEL','MEALS','SOFTWARE','EQUIPMENT','OFFICE','OTHER'))
);
CREATE INDEX idx_expenses_submitter ON expenses(submitter_id);
CREATE INDEX idx_expenses_status    ON expenses(status);
CREATE INDEX idx_expenses_team      ON expenses(team_id);

--changeset elie:0005-receipts
CREATE TABLE receipts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id        BIGINT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    storage_key       VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255),
    content_type      VARCHAR(100),
    size_bytes        BIGINT,
    uploaded_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_receipts_expense ON receipts(expense_id);
