--liquibase formatted sql

--changeset elie:0010-journal-entries
CREATE TABLE journal_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date  DATE        NOT NULL,
    memo        VARCHAR(255),
    source_type VARCHAR(40),
    source_id   BIGINT,
    created_by  BIGINT REFERENCES users(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_journal_entries_source ON journal_entries(source_type, source_id);

--changeset elie:0011-journal-lines
CREATE TABLE journal_lines (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id    BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    account_id  BIGINT NOT NULL REFERENCES accounts(id),
    amount      NUMERIC(14,2) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT chk_journal_lines_amount_nonzero CHECK (amount <> 0)
);
CREATE INDEX idx_journal_lines_entry   ON journal_lines(entry_id);
CREATE INDEX idx_journal_lines_account ON journal_lines(account_id);

--changeset elie:0012-fk-expenses-journal-entry
ALTER TABLE expenses
    ADD CONSTRAINT fk_expenses_journal_entry
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id);

-- The double-entry invariant: every journal entry's lines must sum to zero.
-- This is a multi-row rule, so it is enforced by a DEFERRABLE constraint trigger
-- that runs at transaction commit (letting us insert the debit and credit lines
-- one at a time inside a transaction, then validate the whole entry).
--changeset elie:0013-balance-function splitStatements:false
CREATE OR REPLACE FUNCTION arca_check_entry_balanced() RETURNS trigger AS $func$
DECLARE
    v_entry_id BIGINT;
    v_sum      NUMERIC(14,2);
    v_count    INT;
BEGIN
    v_entry_id := COALESCE(NEW.entry_id, OLD.entry_id);
    SELECT COALESCE(SUM(amount), 0), COUNT(*)
      INTO v_sum, v_count
      FROM journal_lines
     WHERE entry_id = v_entry_id;
    IF v_count > 0 AND v_sum <> 0 THEN
        RAISE EXCEPTION 'Journal entry % is unbalanced: lines sum to % (must be 0)', v_entry_id, v_sum
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$func$ LANGUAGE plpgsql;

--changeset elie:0014-balance-trigger
CREATE CONSTRAINT TRIGGER trg_journal_lines_balanced
    AFTER INSERT OR UPDATE OR DELETE ON journal_lines
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION arca_check_entry_balanced();
